### ISSUE TITLE
[Performance] add eo:cloud_cover

### ISSUE THREAD

**Issue by jdries** [DHI-GRAS/worldwater-toolbox#4]
For loading sentinel-2 data, adding a basic cloud cover filter avoid reading useless data.

This shows how to set the cloudcover to max 85%. The actual percentage may depend on the application, but even setting it to 99% is still relevant, because there are quite a number of products that are completely clouded.
```
s2_properties = {"eo:cloud_cover": lambda v: v <= 85}

s2_cube = connection.load_collection(
    'SENTINEL2_L2A_SENTINELHUB',
    spatial_extent=spatial_extent,
    temporal_extent=[start_date_exclusion, end_date],
    bands=['B02', 'B03', 'B04', 'B08', 'sunAzimuthAngles', 'sunZenithAngles'],
    properties=s2_properties
)

s2_cube_masking = connection.load_collection(
    'SENTINEL2_L2A_SENTINELHUB',
    spatial_extent=spatial_extent,
    temporal_extent=[start_date_exclusion, end_date],
    bands=['CLP', 'SCL'],
    properties=s2_properties
)

```

## Results
Again, test on a small area, resulting in a 30% decrease in cpu here.

*Before*
CPU usage 24,246 cpu-seconds
Wall time 286 seconds
Memory usage 61,440,630 mb-seconds
Sentinelhub 1,357 sentinelhub_processing_unit

*After*
CPU usage 15,982 cpu-seconds
Wall time 214 seconds
Memory usage 40,471,863 mb-seconds
Sentinelhub 764 sentinelhub_processing_unit

**Comment by sulova** [comment]
Thanks Jeroen ! It works faster.

**Comment by dadr94** [comment]
While this may lead to performance improvements, I’d argue it’s more of a methodological change that may have unintended consequences. The ideal solution should be able to handle all imagery. 

There may be use cases where the user is only interested in 5% (or less) of the scene e.g. a reservoir. In cloudy tropical regions setting this threshold too low, may remove too much imagery.  Additionally, the accuracy of the scene-cloud percentage is uncertain, and should not be relied upon entirely.

I recommend we make the default settings high e.g. 99%, but ensure the user is aware of potential performance improvements in the documentation if they wish to enable them for their use case.

**Comment by sulova** [comment]
Thanks Dan. 

Can we agree that we leave high value by default and add this the cloud cover threshold as an input parameter chosen by a user along with ecoregion and date inputs?

**Comment by jdries** [comment]
Great! Even a high default has a lot of effect.
Note that you can even test how many additional pixels you actually get for different thresholds, you may notice that there's not a lot of pixels that remain...
