### ISSUE TITLE
[Performance] process graph caching

### ISSUE THREAD

**Issue by jdries** [DHI-GRAS/worldwater-toolbox#5]
We prepared an important improvement on the openeo-dev backend. It is not yet fully tested and integrated, so needs to be enabled with a feature flag:
job_options={"node_caching":True}

We see quite a big improvement in performance by setting this, combined with the other two optimizations, it is about 5 times more efficient compared to the original version.

**Comment by sulova** [comment]
I can confirm that the performance has been improved when we involved all changes (node_caching, cloud cover and  sar data mask). This is really great and thank you for looking at this.

However, when we tried to increase the spatial extent to a slightly bigger area then we get the error in notebook: 

```
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?66c3f0da-e342-4a6d-9e67-95e0c35c20ee)
---------------------------------------------------------------------------
OpenEoApiError                            Traceback (most recent call last)
Cell In [13], line 207, in WWT(b)
    205 output_save = ouput.save_result(format='netCDF') #GTiff #netCDF
    206 my_job  = output_save.send_job(title= output_name, job_options=job_options)
--> 207 results = my_job.start_and_wait().get_results()
    208 results.download_files(output_name)
    210 print('Done')

File c:\Users\ansu\Miniconda3\envs\widget\lib\site-packages\openeo\rest\job.py:183, in BatchJob.start_and_wait(self, print, max_poll_interval, connection_retry_interval, soft_error_max)
    181 # TODO: make `max_poll_interval`, `connection_retry_interval` class constants or instance properties?
    182 print_status("send 'start'")
--> 183 self.start_job()
    185 # TODO: also add  `wait` method so you can track a job that already has started explicitly
    186 #   or just rename this method to `wait` and automatically do start if not started yet?
    187 
    188 # Start with fast polling.
    189 poll_interval = min(5, max_poll_interval)

File c:\Users\ansu\Miniconda3\envs\widget\lib\site-packages\openeo\rest\job.py:90, in BatchJob.start_job(self)
     86 """ Start / queue a job for processing."""
     87 # POST /jobs/{job_id}/results
     88 # TODO: rename to just `start`? #280
     89 # TODO: return self, to allow chained calls
---> 90 self.connection.post("/jobs/{}/results".format(self.job_id), expected_status=202)
...
    150     else:
    151         exception = OpenEoApiError(http_status_code=status_code, message=text)
--> 152 raise exception

OpenEoApiError: [400] BadRequest: requirement failed: metadata_properties are not supported yet (ref: r-37dd8b19063c4f398cb115d76c67e00e
```
ID:  j-a373e90735d449dbaadc3312bbc7ebb6

Status in web editor says: **created** but it does not fail. Could you explain how to overcome this problem?

This is the spatial extent applied: `Spatial Extent: {'west': -100.53314208984376, 'east': -99.36721801757814, 'south': 19.332526369847702, 'north': 19.591491047978664, 'crs': 4326}`

**Comment by sulova** [comment]
@jdries, did you have time to look at this?

**Comment by jdries** [comment]
Hi @sulova ,
we just redeployed the latest changes to production.
Can you try running it there, I think this specific error only occurs on openeo-dev.

**Comment by sulova** [comment]
Hey @jdries, 
there is a small progress, the jobs were running but failed afterwards. 
used backend: **https://openeo.vito.be**
j-67408f6fd3e748398ceae08670d04f32
j-4bf62623bd1d4675a89e9bc57aa67266
You should check  error messages on editor it is too long to copy.

**Comment by sulova** [comment]
It took quite a long time: 
CPU usage 528,206 cpu-seconds
Wall time: 7,605 seconds
Memory usage: 1,334,014,859 mb-seconds
